spring:
#  data:
#    redis:
#      host: localhost
#      port: 6379
  jpa:
    generate-ddl: true
    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5433/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-timeout: 10000
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema;


app:
  redis:
    enable: true
  cache:
    cacheNames:
      - "allByCategoryName"
      - "oneByTitleAndAuthor"
    caches:
      allByCategoryName:
        lifeTime: 12m
      oneByTitleAndAuthor:
        lifeTime: 12m
    cache-type: "redis"

